# db setting
# default db host
DB_HOST: '127.0.0.1'
# db driver (support mysql, postgresql, sqlite, sql server)
DB_DRIVER: 'mysql' 
# default db port
DB_PORT: '3306'
# default db name
DB_NAME: 'zhuiyi'
# db user
DB_USER: 'root'
# db password
DB_PASSWD: 'zhuiyi123'
# db max idle conns
DB_MAX_IDLE_CONNS: 10
# db max open conns
DB_MAX_OPEN_CONNS: 100
# db conn max life time (minutes)
DB_CONN_MAX_LIFETIME: 60
# slow sql
DB_SLOWTHRESHOLD: 5
# db log (silent, error, warn, info)
DB_LOGMODE: 'info'

# cache setting
# cache enable
CACHE_ENABLED: true
# cache host
CACHE_HOST: '127.0.0.1'
# cache port
CACHE_PORT: '30379'
# cache passwd
CACHE_PASSWD: 'zhuiyi123'
# cache pool size
CACHE_POOL_SIZE: 15
# cache minidle conns
CACHE_MINIDLE_CONNS: 10
# cache db
CACHE_DB: 0


# log setting
# log Level （info、debug、error）
LOG_LEVEL: 'info'
# log max age (minutes, default 30 days)
LOG_MAX_AGE: 43200
# log rotation time (minutes, default 1 days)
LOG_ROTATION_TIME: 1140


# runtime setting
# default run mode
RUN_MODE: 'dev'
# debug mode (debug、release、test)
DEBUG_MODE: 'debug'
# HTTP Req Timeout
TIME_DURATION: 10
# page size
PAGE_SIZE: 20
# server port
SERVER_PORT: '32590'
# gRPC port
GRPC_PORT: '25000'


