# default run mode
RUN_MODE: 'dev'
# default db host
DB_HOST: '127.0.0.1'
# default db port
DB_PORT: '3306'
# default db name
DB_NAME: 'gateway'
# default db name
DB_USER: 'root'
# default db name
DB_PASSWD: 'root123'
# db log
DB_LOGMODE: 'Info'
# debug mode
DEBUG_MODE: true
# Log Level
LOG_LEVEL: 'debug'
# HTTP Req Timeout
TIME_DURATION: 10
# page size
PAGE_SIZE: 20
# server port
<<<<<<< HEAD
SERVER_PORT: '8080'
=======
SERVER_PORT: '9090'
>>>>>>> b8c270612e14e4607718108841674329b55671ec
# gRPC port
GRPC_PORT: '22530'


